/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ory.glb -t
*/

import * as THREE from 'three'
import { useGLTF, useTexture, RoundedBox, Text } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { SRGBColorSpace } from 'three'
import { JSX, useMemo } from 'react'
import { useControls, folder } from 'leva'

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh
    Bezel: THREE.Mesh
    Screen: THREE.Mesh
    Loop: THREE.Mesh
    LoopBase: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

// ─── Texture position controls ───────────────────────────────────────────────
const OFFSET_X = 0.001   // shift left (negative) / right (positive)
const OFFSET_Y = 0.024   // shift down (negative) / up (positive)
const SCALE    = 1.2   // 1 = fill screen, 2 = zoom in, 0.5 = zoom out
// ─────────────────────────────────────────────────────────────────────────────

export default function Ory(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/ory.glb') as unknown as GLTFResult

  const texture = useTexture('/oryscreen.png', (t) => {
    t.colorSpace = SRGBColorSpace
    t.needsUpdate = true
  })

  const screenGeometry = useMemo(() => {
    const geo = nodes.Screen.geometry.clone()
    const pos = geo.attributes.position

    geo.computeBoundingBox()
    const b = geo.boundingBox!
    const dx = (b.max.x - b.min.x) || 1
    const dy = (b.max.y - b.min.y) || 1
    const dz = (b.max.z - b.min.z) || 1

    const count = pos.count
    const uvArr = new Float32Array(count * 2)

    const useXZ = dy <= Math.min(dx, dz)

    for (let i = 0; i < count; i++) {
      let rawU: number, rawV: number

      if (useXZ) {
        rawU = (pos.getX(i) - b.min.x) / dx
        rawV = (pos.getZ(i) - b.min.z) / dz
      } else {
        rawU = (pos.getX(i) - b.min.x) / dx
        rawV = (pos.getY(i) - b.min.y) / dy
      }

      // Apply scale (zoom around center) then offset, then flip U for correct orientation
      const u = 1 - ((rawU - 0.5) / SCALE + 0.5 + OFFSET_X)
      const v = 1 - ((rawV - 0.5) / SCALE + 0.5 + OFFSET_Y)

      uvArr[i * 2]     = u
      uvArr[i * 2 + 1] = v
    }

    geo.setAttribute('uv', new THREE.BufferAttribute(uvArr, 2))
    return geo
  }, [nodes.Screen.geometry])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial color="#111111" metalness={1.45} roughness={0.6} />
      </mesh>
      <mesh geometry={nodes.Bezel.geometry} position={[0, 0, -0.245]} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial color="#1a1a1a" metalness={0.75} roughness={0.6} />
      </mesh>
      <mesh geometry={screenGeometry} position={[0, 0, -0.245]} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial
          map={texture}
          emissiveMap={texture}
          emissive="#ffffff"
          emissiveIntensity={0.85}
          roughness={0.90}
          metalness={0.80}
        />
      </mesh>
      <mesh geometry={nodes.Loop.geometry}>
        <meshStandardMaterial color="#0d0d0d" metalness={0.6} roughness={0.65} />
      </mesh>
      <RoundedBox args={[0.40, 0.15, 0.30]} radius={0.06} smoothness={8} position={[0, 1.02, 0]}>
        <meshStandardMaterial color="#000000" metalness={0.6} roughness={0.65} />
      </RoundedBox>

      {/* Left squircle button – 9 o'clock */}
      <group position={[-0.92, 0, -0.04]} rotation={[0, -Math.PI / 2, Math.PI / 2]}>
        <RoundedBox args={[0.40, 0.28, 0.26]} radius={0.1} smoothness={10}>
          <meshStandardMaterial color="#000000" metalness={0.65} roughness={0.5} />
        </RoundedBox>
        <RoundedBox args={[0.29, 0.185, 0.085]} radius={0.05} smoothness={8} position={[0, 0, 0.1]}>
          <meshStandardMaterial color="#ff4d00" metalness={0.55} roughness={0.45} />
        </RoundedBox>
      </group>

      {/* Right squircle button – 3 o'clock */}
      <group position={[0.92, 0, -0.04]} rotation={[0, Math.PI / 2, Math.PI / 2]}>
        <RoundedBox args={[0.40, 0.28, 0.26]} radius={0.1} smoothness={10}>
          <meshStandardMaterial color="#000000" metalness={0.65} roughness={0.5} />
        </RoundedBox>
        <RoundedBox args={[0.29, 0.185, 0.085]} radius={0.05} smoothness={8} position={[0, 0, 0.1]}>
          <meshStandardMaterial color="#ffffff" metalness={0.55} roughness={0.45} />
        </RoundedBox>
      </group>

      {/* 5 o'clock squircle button */}
      <group position={[0.46, -0.80, -0.04]} rotation={[Math.PI / 2, Math.PI / 6, Math.PI / 95]}>
        <RoundedBox args={[0.40, 0.28, 0.26]} radius={0.1} smoothness={10}>
          <meshStandardMaterial color="#000000" metalness={0.65} roughness={0.5} />
        </RoundedBox>
        <RoundedBox args={[0.29, 0.185, 0.085]} radius={0.05} smoothness={8} position={[0, 0, 0.1]}>
          <meshStandardMaterial color="#ffffff" metalness={0.55} roughness={0.45} />
        </RoundedBox>
      </group>

      {/* 7 o'clock squircle button */}
      <group position={[-0.46, -0.80, -0.04]} rotation={[Math.PI / 2, -Math.PI / 6, Math.PI / 95]}>
        <RoundedBox args={[0.40, 0.28, 0.26]} radius={0.1} smoothness={10}>
          <meshStandardMaterial color="#000000" metalness={0.65} roughness={0.5} />
        </RoundedBox>
        <RoundedBox args={[0.29, 0.185, 0.085]} radius={0.05} smoothness={8} position={[0, 0, 0.1]}>
          <meshStandardMaterial color="#ffffff" metalness={0.55} roughness={0.45} />
        </RoundedBox>
      </group>



    </group>
  )
}

useGLTF.preload('/models/ory.glb')
