import type { Metadata } from 'next'
import { Suspense } from 'react'
import { LoaderProvider } from '@/contexts/LoaderContext'
import AppLoader from '@/components/AppLoader'
import { lamaSans } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${lamaSans.variable} ${lamaSans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LoaderProvider>
          <Suspense fallback={<div className="fixed inset-0 z-9999 bg-black" />}>
            <AppLoader />
          </Suspense>
          {children}
        </LoaderProvider>
      </body>
    </html>
  )
}
